services:
  bookabook-backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/bookabook/backend #FROM main_machine TO docker container

    command:
      sh -c "python3 manage.py runserver 0.0.0.0:8000"