# Generated by Django 4.2.3 on 2023-09-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Страна проживания'),
        ),
        migrations.AddField(
            model_name='user',
            name='fist_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
