# Generated by Django 5.0.4 on 2024-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='death_date',
            field=models.DateTimeField(null=True),
        ),
    ]
