# Generated by Django 4.2.3 on 2023-09-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
