# Generated by Django 5.0.4 on 2024-04-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_authors_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(null=True, to='books.authors', verbose_name="author'(s') of the book"),
        ),
        migrations.AlterField(
            model_name='books',
            name='writing_date',
            field=models.DateTimeField(null=True, verbose_name='date of a publishing date'),
        ),
    ]
