# Generated by Django 5.0.4 on 2024-04-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_authors_birth_date_alter_books_authors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateTimeField(null=True)),
                ('death_date', models.DateTimeField(null=True)),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Страна рождения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='authors',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('genres', models.CharField(choices=[('fiction', 'fiction'), ('novel', 'novel'), ('narrative', 'narrative'), ('mystery', 'mystery'), ('rom-novel', 'romance novel'), ('sci-fict', 'science fiction'), ('thriller', 'thriller'), ('hist-fic', 'historical fiction'), ('gen-fic', 'genre fiction')], default='fiction', max_length=30)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('writing_date', models.DateTimeField(null=True, verbose_name='date of a publishing date')),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('authors', models.ManyToManyField(null=True, to='books.author', verbose_name="author'(s') of the book")),
            ],
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
