# Generated by Django 5.0.4 on 2024-04-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_author_description_alter_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genres',
            new_name='genre',
        ),
    ]
