# Generated by Django 4.2.3 on 2023-09-27 09:03

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_author_birth_year_alter_author_death_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[apps.books.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[apps.books.models.validate_year]),
        ),
    ]
