# Generated by Django 5.0.4 on 2024-04-13 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_genres_book_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'fiction'), ('novel', 'novel'), ('narrative', 'narrative'), ('mystery', 'mystery'), ('rom-novel', 'romance novel'), ('sci-fict', 'science fiction'), ('thriller', 'thriller'), ('hist-fic', 'historical fiction'), ('gen-fic', 'genre fiction'), ('horror', 'horror'), ('tragedy', 'tragedy')], default='fiction', max_length=30),
        ),
    ]
