# Generated by Django 5.0.4 on 2024-04-13 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='rating',
            new_name='rating_review',
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
            preserve_default=False,
        ),
    ]
